---

- hosts: all
  gather_facts: true
  become: true
  

  tasks:
          - ios_facts:

          - name: send email if task failed
            mail:
                    host: localhost
                    port: 25
                    to: rohit.patil@hal.hitachi.com
                    subject: switch ios patching check failed for {{ inventory_hostname }}
                    body: space check failed for {{ inventory_hostname }}, please recheck the space on flashi
          
