---
 - hosts: linux
   become: true
   gather_facts: false


   tasks:
        - name: create directory
          ansible.builtin.file:
                  path: /home/netsec/cdate
                  state: directory
                 
                 
       
